// Source-level event contract; actual Material navigation is browser-tested separately.
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {test} from 'node:test';
import {runInNewContext} from 'node:vm';
const source=readFileSync(new URL('../../docs/javascripts/consent-settings-keyboard.js',import.meta.url),'utf8');
function target(){const listeners={};return{checked:false,attributes:{},addEventListener(type,fn){(listeners[type]??=[]).push(fn);},dispatchEvent(event){for(const fn of listeners[event.type]??[])fn(event);},setAttribute(k,v){this.attributes[k]=v;},focus(){this.focused=true;}};}
function setup(){const search=target(),drawer=target(),searchTrigger=target(),drawerTrigger=target(),frames=[];const doc=Object.assign(target(),{readyState:'complete',getElementById(id){return{__search:search,__drawer:drawer}[id]??null;},querySelector(selector){if(selector.includes('consent'))return null;return selector.includes('__search')?searchTrigger:drawerTrigger;}});runInNewContext(source,{document:doc,Event:class{constructor(type){this.type=type;}},requestAnimationFrame(fn){frames.push(fn);}});return{doc,search,drawer,searchTrigger,drawerTrigger,flush(){frames.splice(0).forEach(fn=>fn());}};}
function key(value){return{type:'keydown',key:value,defaultPrevented:false,stopped:false,preventDefault(){this.defaultPrevented=true;},stopPropagation(){this.stopped=true;}};}
test('Enter/Space own exactly one UI toggle; other keys and zero-detail clicks remain native',()=>{const d=setup();for(const name of ['search','drawer']){const control=d[name+'Trigger'];for(const value of ['Enter',' ']){const event=key(value);control.dispatchEvent(event);assert.equal(event.stopped,true);assert.equal(event.defaultPrevented,true);assert.equal(d[name].checked,value==='Enter');}const other=key('a');control.dispatchEvent(other);assert.equal(other.stopped,false);const click={type:'click',detail:0,preventDefault(){throw Error('AT click must remain native');}};control.dispatchEvent(click);assert.equal(control.attributes.role,'button');}});
test('Escape closes search first, preserves underlying drawer, then returns focus to its owner',()=>{const d=setup();d.search.checked=d.drawer.checked=true;d.doc.dispatchEvent(key('Escape'));d.flush();assert.equal(d.search.checked,false);assert.equal(d.drawer.checked,true);assert.equal(d.searchTrigger.focused,true);assert.equal(d.drawerTrigger.focused,undefined);d.doc.dispatchEvent(key('Escape'));d.flush();assert.equal(d.drawer.checked,false);assert.equal(d.drawerTrigger.focused,true);});
test('reopened surface does not lose focus to delayed close callback',()=>{const d=setup();d.search.checked=true;d.doc.dispatchEvent(key('Escape'));d.search.checked=true;d.flush();assert.equal(d.searchTrigger.focused,undefined);});
