# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x12\x61ssembly.common.v1\"<\n\x07\x41gentId\x12\x0e\n\x06org_id\x18\x01 \x01(\t\x12\x0f\n\x07team_id\x18\x02 \x01(\t\x12\x10\n\x08\x61gent_id\x18\x03 \x01(\t\"\x1c\n\tTimestamp\x12\x0f\n\x07unix_ms\x18\x01 \x01(\x03*R\n\x08\x44\x65\x63ision\x12\x18\n\x14\x44\x45\x43ISION_UNSPECIFIED\x10\x00\x12\t\n\x05\x41LLOW\x10\x01\x12\x08\n\x04\x44\x45NY\x10\x02\x12\x0b\n\x07PENDING\x10\x03\x12\n\n\x06REDACT\x10\x04*\x8a\x01\n\nActionType\x12\x16\n\x12\x41\x43TION_UNSPECIFIED\x10\x00\x12\x0c\n\x08LLM_CALL\x10\x01\x12\r\n\tTOOL_CALL\x10\x02\x12\x12\n\x0e\x46ILE_OPERATION\x10\x03\x12\x10\n\x0cNETWORK_CALL\x10\x04\x12\x10\n\x0cPROCESS_EXEC\x10\x05\x12\x0f\n\x0b\x41GENT_SPAWN\x10\x06*M\n\x08RiskTier\x12\x14\n\x10RISK_UNSPECIFIED\x10\x00\x12\x07\n\x03LOW\x10\x01\x12\n\n\x06MEDIUM\x10\x02\x12\x08\n\x04HIGH\x10\x03\x12\x0c\n\x08\x43RITICAL\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DECISION']._serialized_start=128
  _globals['_DECISION']._serialized_end=210
  _globals['_ACTIONTYPE']._serialized_start=213
  _globals['_ACTIONTYPE']._serialized_end=351
  _globals['_RISKTIER']._serialized_start=353
  _globals['_RISKTIER']._serialized_end=430
  _globals['_AGENTID']._serialized_start=36
  _globals['_AGENTID']._serialized_end=96
  _globals['_TIMESTAMP']._serialized_start=98
  _globals['_TIMESTAMP']._serialized_end=126
# @@protoc_insertion_point(module_scope)
