# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import policy_pb2 as policy__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in policy_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PolicyServiceStub(object):
    """PolicyService handles path ② (runtime → gateway) — the hot path for every
    agent action. Target latency: < 5 ms p99.

    Consumed by: aa-runtime/src/gateway_client.rs (client side)
    aa-gateway/src/policy_engine.rs   (server side)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckAction = channel.unary_unary(
                '/assembly.policy.v1.PolicyService/CheckAction',
                request_serializer=policy__pb2.CheckActionRequest.SerializeToString,
                response_deserializer=policy__pb2.CheckActionResponse.FromString,
                _registered_method=True)
        self.BatchCheck = channel.unary_unary(
                '/assembly.policy.v1.PolicyService/BatchCheck',
                request_serializer=policy__pb2.BatchCheckRequest.SerializeToString,
                response_deserializer=policy__pb2.BatchCheckResponse.FromString,
                _registered_method=True)
        self.OpControlStream = channel.unary_stream(
                '/assembly.policy.v1.PolicyService/OpControlStream',
                request_serializer=policy__pb2.OpControlSubscribeRequest.SerializeToString,
                response_deserializer=policy__pb2.OpControlMessage.FromString,
                _registered_method=True)


class PolicyServiceServicer(object):
    """PolicyService handles path ② (runtime → gateway) — the hot path for every
    agent action. Target latency: < 5 ms p99.

    Consumed by: aa-runtime/src/gateway_client.rs (client side)
    aa-gateway/src/policy_engine.rs   (server side)
    """

    def CheckAction(self, request, context):
        """CheckAction evaluates a single action before the agent dispatches it.
        Called on every intercepted action — must be as fast as possible.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchCheck(self, request, context):
        """BatchCheck pre-warms the policy cache for a set of anticipated actions.
        Called at agent startup or when entering a new task context.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpControlStream(self, request, context):
        """OpControlStream is the gateway → SDK push channel for op-lifecycle
        signals (pause / resume / terminate). The SDK opens the stream once
        per agent process at startup; the gateway pushes one OpControlMessage
        per OpsRegistry transition matching the subscriber's agent_id. See
        AAASM-1653 (PR-D of AAASM-1422); SDK-side consumers ship in PR-E
        (Python), PR-F (Node), and PR-G (Go).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PolicyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckAction': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckAction,
                    request_deserializer=policy__pb2.CheckActionRequest.FromString,
                    response_serializer=policy__pb2.CheckActionResponse.SerializeToString,
            ),
            'BatchCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchCheck,
                    request_deserializer=policy__pb2.BatchCheckRequest.FromString,
                    response_serializer=policy__pb2.BatchCheckResponse.SerializeToString,
            ),
            'OpControlStream': grpc.unary_stream_rpc_method_handler(
                    servicer.OpControlStream,
                    request_deserializer=policy__pb2.OpControlSubscribeRequest.FromString,
                    response_serializer=policy__pb2.OpControlMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'assembly.policy.v1.PolicyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('assembly.policy.v1.PolicyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PolicyService(object):
    """PolicyService handles path ② (runtime → gateway) — the hot path for every
    agent action. Target latency: < 5 ms p99.

    Consumed by: aa-runtime/src/gateway_client.rs (client side)
    aa-gateway/src/policy_engine.rs   (server side)
    """

    @staticmethod
    def CheckAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/assembly.policy.v1.PolicyService/CheckAction',
            policy__pb2.CheckActionRequest.SerializeToString,
            policy__pb2.CheckActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/assembly.policy.v1.PolicyService/BatchCheck',
            policy__pb2.BatchCheckRequest.SerializeToString,
            policy__pb2.BatchCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpControlStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/assembly.policy.v1.PolicyService/OpControlStream',
            policy__pb2.OpControlSubscribeRequest.SerializeToString,
            policy__pb2.OpControlMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
